import { UNIFORM_GOLD_ICONS, UNIFORM_CYBER_ICONS } from '../utils/categoryIcons';
import type { GameDemoItem, RtpGimmickConfig, ResponsibleLegalConfig } from '../types';
import { generateGameFallbackBadge } from '../utils/gameIcons';

export interface CategoryProviderItem {
  id: string;
  title: string;
  category: string;
  imageUrl: string;
  linkUrl: string;
  badge?: string;
  hot?: boolean;
}

export interface NavCategoryItem {
  key: string;
  name: string;
  iconClass: string;
  badge?: string;
  iconImg?: string;
  items: CategoryProviderItem[];
}

export const CATEGORY_GAMES_DATABASE: NavCategoryItem[] = [
  {
    key: 'slots',
    name: 'Slots',
    iconClass: 'fa-solid fa-gamepad',
    badge: 'HOT',
    items: [
      {
        id: 'slot-pragmatic',
        title: 'PRAGMATIC',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/images/ppslot.gif?v=1.0',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-pgsoft',
        title: 'PGSOFT',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/images/pgsoft.gif?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-cq9',
        title: 'CQ9',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/cq9_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-besoft',
        title: 'BESOFT',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/besoft_slot.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-cosmoplay',
        title: 'COSMO PLAY',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/cosmo_slot.png?v=0.2',
        linkUrl: '#',
        badge: 'NEW',
      },
      {
        id: 'slot-microgaming',
        title: 'MICRO GAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/images/mg_rng.gif',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-joker',
        title: 'JOKER',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/jk_slot.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-spadegaming',
        title: 'SPADE GAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sg_slot.gif?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-jili',
        title: 'JILI',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/images/jili.gif?v=1.0',
        linkUrl: '#',
      },
      {
        id: 'slot-fastspin',
        title: 'FASTSPIN',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/fastspin_slot.gif?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-bng',
        title: 'BNG',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/booongo_slot.gif?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-playtech',
        title: 'PLAYTECH',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/pt_slot.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-fatpanda',
        title: 'Pragmatic Play POP',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/fatpanda_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-wow',
        title: 'WOW GAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/wow_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-sigma',
        title: 'PRIME SIGMA GAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/images/sigmagaming_slot.gif?v=2.0',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-askmeslot',
        title: 'ASKMESLOT',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/askme_slot.png?v=0.2',
        linkUrl: '#',
        badge: 'NEW',
      },
      {
        id: 'slot-habanero',
        title: 'HABANERO',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hb_slot.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-advantplay',
        title: 'ADVANTPLAY',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/advantplay_slot.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-hacksaw',
        title: 'HACKSAW',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hacksaw_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-live22',
        title: 'LIVE22',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/live22_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-nolimit',
        title: 'NOLIMITCITY',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/nolimitcity_slot.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-nextspin',
        title: 'NEXTSPIN',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/nextspin_slot.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'slot-playstar',
        title: 'PLAYSTAR',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/playstar_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-relax',
        title: 'RELAX GAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/relax_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-skywind',
        title: 'SKYWIND',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/skywind_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-aigaming',
        title: 'AI GAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/aigaming_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-redtiger',
        title: 'REDTIGER',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/redtiger_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-netent',
        title: 'NETENT',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/redtiger_net_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-playngo',
        title: 'PLAYNGO',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/playngo_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-hotdog',
        title: 'HOTDOG GAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hotdog_slot.png?v=0.2',
        linkUrl: '#',
        badge: 'NEW',
      },
      {
        id: 'slot-dstplay',
        title: 'DST PLAY',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/dst_slot.png?v=0.2',
        linkUrl: '#',
        badge: 'NEW',
      },
      {
        id: 'slot-booming',
        title: 'BOOMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ttg_booming_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-fachai',
        title: 'FACHAI',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/fachai_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-jdb',
        title: 'JDB',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/jdb_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-dragoonsoft',
        title: 'DRAGOON SOFT',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/dragoon_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-5gaming',
        title: '5GAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/5gaming_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-apollo777',
        title: 'APOLLO777',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/apollo777_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-ygg',
        title: 'YGG',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/yggslot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-kagaming',
        title: 'KA GAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/kagaming_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-nagagames',
        title: 'NAGA GAMES',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/nagagames_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-onegame',
        title: 'One Game',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/onegame_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-bgaming',
        title: 'BGAMING',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/bgaming_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-gmw',
        title: 'GMW',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/gmw_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-uu',
        title: 'UU Slot',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/uu_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-pegasus',
        title: 'PEGASUS',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/pegasus_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-btg',
        title: 'BTG',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/btg_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-liteplay',
        title: 'LITEPLAY',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/liteplay_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-sbo',
        title: 'SBO',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sbo_slot.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'slot-568win',
        title: '568 WIN',
        category: 'Slots',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sbo_568win_slot.png?v=0.2',
        linkUrl: '#',
      },
    ],
  },
  {
    key: 'live-games',
    name: 'Live Games',
    iconClass: 'fa-solid fa-tower-broadcast',
    badge: 'HOT',
    iconImg: 'https://files.sitestatic.net/images/live_game_icon.gif?v=1',
    items: [
      {
        id: 'live-bacbo',
        title: 'BAC BO',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/198.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-12d',
        title: '12D',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/41.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-24d',
        title: '24D',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/42.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-36d',
        title: '36D',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/44.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-48d',
        title: '48D',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/43.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-60d',
        title: '60D',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/173.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-sicbo',
        title: 'Sicbo',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/46.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-oglokball',
        title: 'Oglok Ball',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/49.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-oglokdice',
        title: 'Oglok Dice',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/159.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-6colors',
        title: '6 Colors',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/155.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-12colors',
        title: '12 Colors',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/160.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-abjad',
        title: 'ABJAD',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_number/197.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-jmarble',
        title: 'JMARBLE',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/jmarble_rng.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'live-ezugi',
        title: 'EZUGI',
        category: 'Live Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ezugi_rng.png?v=0.2',
        linkUrl: '#',
      },
    ],
  },
  {
    key: 'sports',
    name: 'Sports',
    iconClass: 'fa-solid fa-futbol',
    badge: 'TOP',
    items: [
      {
        id: 'sport-cmd',
        title: 'CMD SPORTS',
        category: 'Sports',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/cmds_sport.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'sport-wbet',
        title: 'WBET Sport',
        category: 'Sports',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/wbet_sport.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'sport-sbo',
        title: 'SBO SPORTS',
        category: 'Sports',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sbo_sport_new.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'sport-saba',
        title: 'SABA SPORTS',
        category: 'Sports',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ibc_sport.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'sport-ug',
        title: 'UNITED GAMING',
        category: 'Sports',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ug_sport.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'sport-bti',
        title: 'BTI SPORTS',
        category: 'Sports',
        imageUrl: 'https://files.sitestatic.net/images/bti_sport.gif',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'sport-virtual',
        title: 'Virtual Sport',
        category: 'Sports',
        imageUrl: 'https://files.sitestatic.net/images/ppslot.gif?v=1.0',
        linkUrl: '#',
      },
      {
        id: 'sport-im',
        title: 'IM SPORT',
        category: 'Sports',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/im_sport.png?v=0.2',
        linkUrl: '#',
      },
    ],
  },
  {
    key: 'casino',
    name: 'Casino',
    iconClass: 'fa-solid fa-dice',
    badge: 'LIVE',
    items: [
      {
        id: 'casino-pragmatic',
        title: 'PRAGMATIC',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/images/ppslot.gif?v=1.0',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'casino-playtech',
        title: 'PLAYTECH',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/pt_casino.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'casino-evo',
        title: 'EVO',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/evo_casino.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'casino-sexy',
        title: 'SEXY',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sb_casino.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'casino-ar',
        title: 'AR CASINO',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ar_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-iconic21',
        title: 'ICONIC21',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/beter_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-ezugi',
        title: 'EZUGI',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ezugi_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-allbet',
        title: 'ALLBET',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/allbet_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-microgaming',
        title: 'MICROGAMING',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/images/mg_rng.gif',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'casino-sagaming',
        title: 'SA',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sa_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-biggaming',
        title: 'BIG GAMING',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sbo_big_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-568win',
        title: '568win',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sbo_casino_new.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-opus',
        title: 'OPUS',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/opus_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-dreamgaming',
        title: 'DREAM GAMING',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/dream_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-wm',
        title: 'WM',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/wm_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-w',
        title: 'W',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/w_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-skywind',
        title: 'SKYWIND',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/skywind_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-ai',
        title: 'AI',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ai_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-via',
        title: 'VIA',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/via_casino.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'casino-mikiworld',
        title: 'MIKIWORLD',
        category: 'Casino',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/miki_casino.png?v=0.2',
        linkUrl: '#',
      },
    ],
  },
  {
    key: 'cockfight',
    name: 'Sabung Ayam',
    iconClass: 'fa-solid fa-feather',
    badge: 'HOT',
    items: [
      {
        id: 'cf-sv388',
        title: 'SV388',
        category: 'Sabung Ayam',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sv388_cf.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'cf-cfa88',
        title: 'CFA88',
        category: 'Sabung Ayam',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/cfa88_cf.png?v=0.2',
        linkUrl: '#',
      },
    ],
  },
  {
    key: 'fish-hunter',
    name: 'Tembak Ikan',
    iconClass: 'fa-solid fa-fish',
    badge: 'SERU',
    items: [
      {
        id: 'fish-joker',
        title: 'JOKER',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/jk_fishing.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'fish-spade',
        title: 'SPADE GAMING',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/sg_fishing.gif?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'fish-cq9',
        title: 'CQ9',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/cq9_fishing.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'fish-jili',
        title: 'JILI',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/images/jili.gif?v=1.0',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'fish-skywind',
        title: 'SKYWIND',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/skywind_fishing.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'fish-dragoon',
        title: 'DRAGOON SOFT',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/dragoon_fishing.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'fish-ka',
        title: 'KA GAMING',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/kagaming_fishing.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'fish-fastspin',
        title: 'FASTSPIN',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/fastspin_fishing.gif?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'fish-fachai',
        title: 'FACHAI',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/fachai_fishing.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'fish-jdb',
        title: 'JDB',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/jdb_fishing.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'fish-ksgaming',
        title: 'KSGAMING',
        category: 'Tembak Ikan',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ksgaming_rng.png?v=2.0',
        linkUrl: '#',
      },
    ],
  },
  {
    key: 'lottery',
    name: 'Lotre',
    iconClass: 'fa-solid fa-ticket',
    badge: 'HOT',
    items: [
      {
        id: 'lot-hongkong',
        title: 'Hongkong Win',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/235.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'lot-sydney',
        title: 'Sydney Prize',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/230.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'lot-amazon',
        title: 'Amazon 4D',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/22.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'lot-king',
        title: 'King 4D',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/23.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'lot-hkgrand',
        title: 'Hongkong Grand 4D',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/21.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'lot-shanghai',
        title: 'Shanghai Hero 4D',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/20.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'lot-sgp',
        title: 'Singapore Pools 4D',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/17.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'lot-toto',
        title: 'Malaysia Toto 4D',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/25.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'lot-magnum',
        title: 'Malaysia Magnum 4D',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/24.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'lot-damacai',
        title: 'Malaysia Damacai 4D',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/hkgp_togel/26.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'lot-nex4d',
        title: 'NEX4D',
        category: 'Lotre',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/nex4d_togel.png?v=0.2',
        linkUrl: '#',
      },
    ],
  },
  {
    key: 'egames',
    name: 'E-Games',
    iconClass: 'fa-solid fa-ghost',
    items: [
      {
        id: 'eg-pp',
        title: 'PRAGMATIC',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/pp_rng.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'eg-jili',
        title: 'JILI',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/images/jili.gif?v=1.0',
        linkUrl: '#',
      },
      {
        id: 'eg-microgaming',
        title: 'MICROGAMING',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/images/mg_rng.gif',
        linkUrl: '#',
      },
      {
        id: 'eg-joker',
        title: 'JOKER',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/jk_rng.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'eg-ggsoft',
        title: 'GGSOFT',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ggsoft_rng.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'eg-dstplay',
        title: 'DST PLAY',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/dst_rng.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'eg-gemini',
        title: 'GEMINI',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/gemini_rng.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'eg-dragoon',
        title: 'DRAGOONSOFT',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/dragoon_rng.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'eg-mikiworld',
        title: 'MIKIWORLD',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/miki_rng.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'eg-chicky',
        title: 'Chicky Run',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/pgsoft_rng/1738001.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'eg-bgaming',
        title: 'BGAMING',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/bgaming_rng.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'eg-spribe',
        title: 'SPRIBE',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/spribe_rng.png?v=0.2',
        linkUrl: '#',
        hot: true,
      },
      {
        id: 'eg-sigma',
        title: 'PRIME SIGMA GAMING',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/images/sigmagaming_slot.gif?v=2.0',
        linkUrl: '#',
      },
      {
        id: 'eg-playtech',
        title: 'PLAYTECH',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/pt_rng.png?v=0.2',
        linkUrl: '#',
      },
      {
        id: 'eg-ksgaming',
        title: 'KSGAMING',
        category: 'E-Games',
        imageUrl: 'https://files.sitestatic.net/assets/imgs/game_logos/100x70/ksgaming_rng.png?v=2.0',
        linkUrl: '#',
      },
    ],
  },
];

/**
 * Curated Summary / Representative Category Icons for Landing Pages
 * (Ringkasan Icon Kategori Resmi Seragam Emas Mewah & 100% Anti-Gagal Muat)
 */
export const SUMMARY_CATEGORIES: CategoryProviderItem[] = [
  {
    id: 'sum-slots',
    title: 'SLOTS',
    category: 'Pragmatic, PG Soft, Habanero',
    imageUrl: UNIFORM_GOLD_ICONS.slots,
    linkUrl: '#',
    hot: true,
    badge: 'POPULER',
  },
  {
    id: 'sum-livecasino',
    title: 'LIVE CASINO',
    category: 'Evolution, Sexy Baccarat, Pragmatic',
    imageUrl: UNIFORM_GOLD_ICONS.casino,
    linkUrl: '#',
    hot: true,
    badge: 'HOT',
  },
  {
    id: 'sum-livegames',
    title: 'LIVE GAMES',
    category: 'Dingdong, 12D, 24D, Dice 6',
    imageUrl: UNIFORM_GOLD_ICONS.livegames,
    linkUrl: '#',
    badge: 'LIVE',
  },
  {
    id: 'sum-sports',
    title: 'SPORTSBOOK',
    category: 'SBOBET, CMD368, Saba Sports',
    imageUrl: UNIFORM_GOLD_ICONS.sports,
    linkUrl: '#',
    badge: 'PARLAY',
  },
  {
    id: 'sum-sabungayam',
    title: 'SABUNG AYAM',
    category: 'SV388 Cockfight Live HD',
    imageUrl: UNIFORM_GOLD_ICONS.cockfight,
    linkUrl: '#',
    hot: true,
  },
  {
    id: 'sum-tembakikan',
    title: 'TEMBAK IKAN',
    category: 'Joker, Spadegaming, Jili Fish',
    imageUrl: UNIFORM_GOLD_ICONS.fish,
    linkUrl: '#',
  },
  {
    id: 'sum-lotre',
    title: 'TOGEL 4D',
    category: 'Singapore, Hongkong, Sydney, Macau',
    imageUrl: UNIFORM_GOLD_ICONS.lottery,
    linkUrl: '#',
    badge: 'DISKON 66%',
  },
  {
    id: 'sum-egames',
    title: 'ARCADE & E-GAMES',
    category: 'Spribe Aviator, Mines, Crash, Chicky',
    imageUrl: UNIFORM_GOLD_ICONS.egames,
    linkUrl: '#',
    hot: true,
  },
  {
    id: 'sum-promosi',
    title: 'PROMOSI & BONUS',
    category: 'Bonus New Member & Rollingan',
    imageUrl: UNIFORM_GOLD_ICONS.promo,
    linkUrl: '#',
    badge: 'CLAIM',
  },
  {
    id: 'sum-bantuan',
    title: 'PUSAT BANTUAN',
    category: 'Layanan Live Chat 24 Jam Nonstop',
    imageUrl: UNIFORM_GOLD_ICONS.support,
    linkUrl: '#',
  },
];

export const SUMMARY_CYBER_CATEGORIES: CategoryProviderItem[] = [
  {
    id: 'cyb-slots',
    title: 'SLOTS',
    category: 'Pragmatic, PG Soft, Habanero',
    imageUrl: UNIFORM_CYBER_ICONS.slots,
    linkUrl: '#',
    hot: true,
    badge: 'POPULER',
  },
  {
    id: 'cyb-livecasino',
    title: 'LIVE CASINO',
    category: 'Evolution, Sexy Baccarat, Pragmatic',
    imageUrl: UNIFORM_CYBER_ICONS.casino,
    linkUrl: '#',
    hot: true,
    badge: 'HOT',
  },
  {
    id: 'cyb-livegames',
    title: 'LIVE GAMES',
    category: 'Dingdong, 12D, 24D, Dice 6',
    imageUrl: UNIFORM_CYBER_ICONS.livegames,
    linkUrl: '#',
    badge: 'LIVE',
  },
  {
    id: 'cyb-sports',
    title: 'SPORTSBOOK',
    category: 'SBOBET, CMD368, Saba Sports',
    imageUrl: UNIFORM_CYBER_ICONS.sports,
    linkUrl: '#',
    badge: 'PARLAY',
  },
  {
    id: 'cyb-sabungayam',
    title: 'SABUNG AYAM',
    category: 'SV388 Cockfight Live HD',
    imageUrl: UNIFORM_CYBER_ICONS.cockfight,
    linkUrl: '#',
    hot: true,
  },
  {
    id: 'cyb-tembakikan',
    title: 'TEMBAK IKAN',
    category: 'Joker, Spadegaming, Jili Fish',
    imageUrl: UNIFORM_CYBER_ICONS.fish,
    linkUrl: '#',
  },
  {
    id: 'cyb-lotre',
    title: 'TOGEL 4D',
    category: 'Singapore, Hongkong, Sydney, Macau',
    imageUrl: UNIFORM_CYBER_ICONS.lottery,
    linkUrl: '#',
    badge: 'DISKON 66%',
  },
  {
    id: 'cyb-egames',
    title: 'ARCADE & E-GAMES',
    category: 'Spribe Aviator, Mines, Crash',
    imageUrl: UNIFORM_CYBER_ICONS.egames,
    linkUrl: '#',
    hot: true,
  },
  {
    id: 'cyb-promosi',
    title: 'PROMOSI & BONUS',
    category: 'Bonus New Member & Rollingan',
    imageUrl: UNIFORM_CYBER_ICONS.promo,
    linkUrl: '#',
    badge: 'CLAIM',
  },
  {
    id: 'cyb-bantuan',
    title: 'PUSAT BANTUAN',
    category: 'Layanan Live Chat 24 Jam Nonstop',
    imageUrl: UNIFORM_CYBER_ICONS.support,
    linkUrl: '#',
  },
];

/**
 * Returns clean summary category icons for landing page
 */
export function getSummaryCategories(theme: 'gold' | 'cyber' = 'gold'): CategoryProviderItem[] {
  return theme === 'cyber' ? [...SUMMARY_CYBER_CATEGORIES] : [...SUMMARY_CATEGORIES];
}

/**
 * Returns all games from all categories as a single flat array
 */
export function getAllCategoryGames(): CategoryProviderItem[] {
  return CATEGORY_GAMES_DATABASE.flatMap((cat) => cat.items);
}

/**
 * Returns games filtered by category key
 */
export function getGamesByCategory(categoryKey: string): CategoryProviderItem[] {
  if (!categoryKey || categoryKey === 'all') {
    return getAllCategoryGames();
  }
  const cat = CATEGORY_GAMES_DATABASE.find((c) => c.key === categoryKey || c.name.toLowerCase() === categoryKey.toLowerCase());
  return cat ? cat.items : [];
}

/**
 * Authentic Official Demo Games Database with Real Direct Demo Launcher Links
 */
export const OFFICIAL_DEMO_GAMES_DATABASE: GameDemoItem[] = [
  {
    id: 'demo-olympus-1000',
    name: 'Gates of Olympus 1000',
    provider: 'Pragmatic Play',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Gates of Olympus 1000', 'Pragmatic Play'),
    demoUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=id&cur=IDR&gameSymbol=vs20olympx',
    realPlayUrl: '#',
    rtpPercent: 98.8,
    volatility: 'Extreme',
    jamGacor: '00:45 - 03:30 WIB',
    polaSpin: '⚡ 20x Auto | ❌ 30x Manual | 🔥 10x Turbo (DC On)',
    hot: true,
    maxwinX: 'x1000',
  },
  {
    id: 'demo-sweet-bonanza-1000',
    name: 'Sweet Bonanza 1000',
    provider: 'Pragmatic Play',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Sweet Bonanza 1000', 'Pragmatic Play'),
    demoUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=id&cur=IDR&gameSymbol=vs20bonz1000',
    realPlayUrl: '#',
    rtpPercent: 98.2,
    volatility: 'High',
    jamGacor: '11:15 - 14:00 WIB',
    polaSpin: '🔥 10x Turbo | ⚡ 20x Auto | ❌ 50x Cepat',
    hot: true,
    maxwinX: 'x1000',
  },
  {
    id: 'demo-starlight-1000',
    name: 'Starlight Princess 1000',
    provider: 'Pragmatic Play',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Starlight Princess 1000', 'Pragmatic Play'),
    demoUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=id&cur=IDR&gameSymbol=vs20starlightx',
    realPlayUrl: '#',
    rtpPercent: 98.5,
    volatility: 'Extreme',
    jamGacor: '15:30 - 18:45 WIB',
    polaSpin: '❌ 20x Manual | ⚡ 30x Auto | 🔥 15x Turbo',
    hot: true,
    maxwinX: 'x1000',
  },
  {
    id: 'demo-mahjong-ways-2',
    name: 'Mahjong Ways 2',
    provider: 'PG Soft',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Mahjong Ways 2', 'PG Soft'),
    demoUrl: 'https://m.pgsoft-games.com/65/index.html?ot=pgsoft&btt=2&language=id-ID',
    realPlayUrl: '#',
    rtpPercent: 98.9,
    volatility: 'High',
    jamGacor: '19:30 - 22:40 WIB',
    polaSpin: '⚡ 50x Auto | 🔥 30x Turbo | ❌ 10x Manual',
    hot: true,
    maxwinX: 'x100000',
  },
  {
    id: 'demo-mahjong-ways-1',
    name: 'Mahjong Ways',
    provider: 'PG Soft',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Mahjong Ways', 'PG Soft'),
    demoUrl: 'https://m.pgsoft-games.com/74/index.html?ot=pgsoft&btt=2&language=id-ID',
    realPlayUrl: '#',
    rtpPercent: 98.3,
    volatility: 'Medium',
    jamGacor: '18:00 - 21:00 WIB',
    polaSpin: '❌ 20x Manual | ⚡ 40x Auto | 🔥 20x Turbo',
    hot: false,
    maxwinX: 'x25000',
  },
  {
    id: 'demo-lucky-neko',
    name: 'Lucky Neko',
    provider: 'PG Soft',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Lucky Neko', 'PG Soft'),
    demoUrl: 'https://m.pgsoft-games.com/89/index.html?ot=pgsoft&btt=2&language=id-ID',
    realPlayUrl: '#',
    rtpPercent: 97.8,
    volatility: 'Medium',
    jamGacor: '06:00 - 09:30 WIB',
    polaSpin: '❌ 30x Manual | 🔥 20x Turbo | ⚡ 10x Auto',
    hot: true,
    maxwinX: 'x20000',
  },
  {
    id: 'demo-wild-bandito',
    name: 'Wild Bandito',
    provider: 'PG Soft',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Wild Bandito', 'PG Soft'),
    demoUrl: 'https://m.pgsoft-games.com/104/index.html?ot=pgsoft&btt=2&language=id-ID',
    realPlayUrl: '#',
    rtpPercent: 97.5,
    volatility: 'Medium',
    jamGacor: '13:00 - 15:45 WIB',
    polaSpin: '⚡ 30x Auto | ❌ 20x Manual | 🔥 50x Turbo',
    hot: false,
    maxwinX: 'x25000',
  },
  {
    id: 'demo-aztec-gems',
    name: 'Treasures of Aztec',
    provider: 'PG Soft',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Treasures of Aztec', 'PG Soft'),
    demoUrl: 'https://m.pgsoft-games.com/48/index.html?ot=pgsoft&btt=2&language=id-ID',
    realPlayUrl: '#',
    rtpPercent: 98.6,
    volatility: 'High',
    jamGacor: '16:00 - 19:30 WIB',
    polaSpin: '⚡ 40x Auto | 🔥 20x Turbo | ❌ 10x Manual',
    hot: true,
    maxwinX: 'x100000',
  },
  {
    id: 'demo-gatotkaca-1000',
    name: 'Gates of Gatot Kaca 1000',
    provider: 'Pragmatic Play',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Gates of Gatot Kaca 1000', 'Pragmatic Play'),
    demoUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=id&cur=IDR&gameSymbol=vs20gatotx',
    realPlayUrl: '#',
    rtpPercent: 98.4,
    volatility: 'Extreme',
    jamGacor: '21:00 - 23:59 WIB',
    polaSpin: '🔥 20x Turbo | ⚡ 50x Auto | ❌ 10x Manual',
    hot: true,
    maxwinX: 'x1000',
  },
  {
    id: 'demo-sugar-rush-1000',
    name: 'Sugar Rush 1000',
    provider: 'Pragmatic Play',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Sugar Rush 1000', 'Pragmatic Play'),
    demoUrl: 'https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=id&cur=IDR&gameSymbol=vs20sugarrushx',
    realPlayUrl: '#',
    rtpPercent: 98.0,
    volatility: 'Extreme',
    jamGacor: '14:30 - 17:15 WIB',
    polaSpin: '⚡ 10x Auto | ❌ 40x Manual | 🔥 30x Turbo',
    hot: false,
    maxwinX: 'x1000',
  },
  {
    id: 'demo-koi-gate',
    name: 'Koi Gate',
    provider: 'Habanero',
    category: 'Slots',
    iconUrl: generateGameFallbackBadge('Koi Gate', 'Habanero'),
    demoUrl: 'https://demo.habanerosystems.com/games/koigate',
    realPlayUrl: '#',
    rtpPercent: 97.4,
    volatility: 'Medium',
    jamGacor: '08:00 - 11:00 WIB',
    polaSpin: '❌ 20x Manual | ⚡ 10x Auto',
    hot: false,
  },
  {
    id: 'demo-aviator',
    name: 'Aviator Crash',
    provider: 'Spribe',
    category: 'Arcade',
    iconUrl: generateGameFallbackBadge('Aviator', 'Spribe'),
    demoUrl: 'https://spribe.co/games/aviator',
    realPlayUrl: '#',
    rtpPercent: 97.0,
    volatility: 'Medium',
    jamGacor: '24 Jam Nonstop',
    polaSpin: 'Cashout Multiplier 1.5x - 2.0x Konsisten',
    hot: true,
  },
];

export const DEFAULT_RTP_GIMMICK_CONFIG: RtpGimmickConfig = {
  enabled: true,
  enableLiveFluctuation: true,
  updateIntervalSeconds: 120,
  showPolaGacor: true,
  showJamGacor: true,
  showDemoModal: true,
  headline: 'RTP Live & Demo Slot Gacor Hari Ini',
  subheadline: 'Bocoran persentase RTP real-time, jam hoki gacor, pola spin teruji, dan uji coba demo gratis tanpa deposit.',
  demoGames: OFFICIAL_DEMO_GAMES_DATABASE,
};

export const DEFAULT_RESPONSIBLE_LEGAL_CONFIG: ResponsibleLegalConfig = {
  enableAgeGate: true,
  ageLimitText: '18+',
  modalTitle: 'Peringatan Tanggung Jawab & Konfirmasi Usia 18+',
  disclaimerText: 'Platform ini hanya menyajikan informasi edukasi RTP, ulasan game, dan simulasi demo slot untuk hiburan. Akses hanya diperuntukkan bagi pengguna berusia 18 tahun ke atas atau usia legal di yurisdiksi Anda. Tidak ada paksaan atau jaminan keuntungan finansial. Bermainlah dengan bijak dan bertanggung jawab.',
  nonCoerciveBadge: true,
  allowVoluntaryDismiss: true,
  complianceBadges: ['18+', 'responsible-gaming', 'bmm-testlabs', 'gli-certified', 'ssl-secure'],
};
