import JSZip from 'jszip';
import type {
  AmpConfig,
  PortalConfig,
  RegisterConfig,
  SafeLinkConfig,
  CyberShieldConfig,
  CdnScriptConfig,
} from '../types';
import {
  generateAmpHtml,
  generatePortalHtml,
  generateVipRegisterHtml,
  generateSafeLinkHtml,
} from './generator';
import { generateCyberShieldScript } from '../utils/cyberShield';

export interface DeployPackageOptions {
  primaryLanding: 'amp' | 'portal';
  includeHtaccess: boolean;
  includeCloudflareConfig: boolean;
  includeGithubPagesConfig: boolean;
  includeSitemap: boolean;
  includeCyberShield: boolean;
}

export function generateRobotsTxt(ampCanonical: string, isTransitBlocked: boolean = true): string {
  return `# Robots.txt Generated by Suite Landing Page & Portal
User-agent: *
Allow: /
Allow: /amp.html
Allow: /portal.html
${isTransitBlocked ? `Disallow: /safelink.html\nDisallow: /register.html\nDisallow: /api/\nDisallow: /*?token=\nDisallow: /*?ref=` : ''}

# Disallow aggressive security scanners and scraper crawlers
User-agent: Shodan
Disallow: /

User-agent: CensysInspect
Disallow: /

User-agent: SemrushBot
Disallow: /

User-agent: AhrefsBot
Disallow: /

User-agent: MJ12bot
Disallow: /

Sitemap: ${ampCanonical ? ampCanonical.replace(/\/$/, '') : 'https://vip-official.pages.dev'}/sitemap.xml
`;
}

export function generateSitemapXml(ampUrl: string, portalUrl: string): string {
  const dateStr = new Date().toISOString().split('T')[0];
  const domain = ampUrl ? ampUrl.replace(/\/$/, '') : 'https://vip-official.pages.dev';

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${domain}/</loc>
    <lastmod>${dateStr}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>${domain}/amp.html</loc>
    <lastmod>${dateStr}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>${portalUrl || `${domain}/portal.html`}</loc>
    <lastmod>${dateStr}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>`;
}

export function generateHtaccess(brandName: string): string {
  return `# ========================================================
# .htaccess for Apache / LiteSpeed / cPanel (public_html/httpdocs)
# Brand: ${brandName}
# ========================================================

RewriteEngine On

# 1. Force HTTPS
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# 2. Security Headers
<IfModule mod_headers.c>
  Header set X-Content-Type-Options "nosniff"
  Header set X-XSS-Protection "1; mode=block"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  Header always set Permissions-Policy "geolocation=(), microphone=(), camera=()"
</IfModule>

# 3. GZIP / Brotli Compression
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css application/javascript application/json
</IfModule>

# 4. Browser Cache for Static Assets
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType image/jpg "access plus 1 year"
  ExpiresByType image/jpeg "access plus 1 year"
  ExpiresByType image/gif "access plus 1 year"
  ExpiresByType image/png "access plus 1 year"
  ExpiresByType image/webp "access plus 1 year"
  ExpiresByType text/css "access plus 1 month"
  ExpiresByType application/javascript "access plus 1 month"
</IfModule>

# 5. Disable Directory Browsing
Options -Indexes
`;
}

export function generateCloudflareRedirects(): string {
  return `# Cloudflare Pages _redirects file
/daftar /register.html 302
/masuk /portal.html 302
/safe /safelink.html 302
`;
}

export function generateCloudflareHeaders(): string {
  return `/*
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()

/safelink.html
  X-Robots-Tag: noindex, nofollow, noarchive

/register.html
  X-Robots-Tag: noindex, nofollow, noarchive
`;
}

export function generateReadmeDeployment(brand: string): string {
  return `# PANDUAN DEPLOYMENT SUITE: ${brand}

Paket ini berisi kumpulan file HTML siap pakai yang telah divalidasi Google AMP, dilengkapi skema JSON-LD, filter CyberShield, dan optimasi SEO.

---

## 1. Deploy ke Cloudflare Pages (Gratis & Tercepat)
1. Buka [Cloudflare Dashboard](https://dash.cloudflare.com/) > **Workers & Pages** > **Create application** > **Pages**.
2. Pilih tab **Direct Upload** (Upload assets).
3. Buat nama project (contoh: \`${brand.toLowerCase().replace(/[^a-z0-9]/g, '')}-vip\`).
4. Drag & drop folder hasil ekstrak ZIP ini (atau upload folder).
5. Klik **Deploy Site**. Halaman Anda langsung online dalam 5 detik dengan CDN global & proteksi DDoS Cloudflare gratis!

---

## 2. Deploy ke GitHub Pages
1. Buat repository baru di GitHub (contoh: \`landing-${brand.toLowerCase().replace(/[^a-z0-9]/g, '')}\`).
2. Upload semua file dalam paket ini ke root repository (\`main\` branch).
3. Masuk ke **Settings** > **Pages** > Pada *Branch*, pilih \`main\` / \`/ (root)\`, lalu klik **Save**.
4. Website akan aktif di \`https://username.github.io/repository-name/\`.
*(File \`.nojekyll\` sudah disertakan agar semua asset terbaca sempurna).*

---

## 3. Deploy ke cPanel / httpdocs (Hosting Lokal / Nginx / Apache)
1. Buka **cPanel** > **File Manager**.
2. Masuk ke direktori domain Anda (biasanya \`public_html\` atau \`httpdocs\`).
3. Upload file ZIP ini lalu klik **Extract**.
4. Pastikan file \`index.html\` dan \`.htaccess\` berada di root folder domain.
5. Selesai! Website siap diakses dengan HTTPS otomatis.

---

## 4. Buka di Antigravity IDE / VS Code / Live Server
1. Buka folder ini di editor (Antigravity IDE / VS Code).
2. Jalankan ekstensi **Live Server** atau command \`npx serve .\`.
3. Buka browser di \`http://localhost:3000\` atau \`http://localhost:5500\`.

---

## Struktur File dalam Paket:
- \`index.html\`: Halaman utama (sesuai pilihan: AMP atau Portal Utama)
- \`amp.html\`: Halaman Google AMP Valid dengan running text & Rich Snippet
- \`portal.html\`: Portal responsif dengan etalase game & provider lengkap
- \`register.html\`: Form registrasi VIP mandiri & verifikasi WhatsApp
- \`safelink.html\`: Halaman SafeLink / bridge anti-bot & token enkripsi
- \`cyber-shield.js\`: Engine proteksi Anti-Inspect (F12, Ctrl+U) & anti-copy
- \`robots.txt\`: Direktif perayapan mesin pencari & pemblokir scanner ilegal
- \`sitemap.xml\`: XML Sitemap standar Google Search Console
- \`_redirects\` & \`_headers\`: Konfigurasi keamanan Cloudflare Pages
- \`.htaccess\`: Konfigurasi server Apache / LiteSpeed cPanel
- \`.nojekyll\`: Bypass parser GitHub Pages
`;
}

export async function createDeployZip(
  ampConfig: AmpConfig,
  portalConfig: PortalConfig,
  registerConfig: RegisterConfig,
  safelinkConfig: SafeLinkConfig,
  cyberShieldConfig: CyberShieldConfig,
  cdnScripts: CdnScriptConfig,
  options: DeployPackageOptions = {
    primaryLanding: 'amp',
    includeHtaccess: true,
    includeCloudflareConfig: true,
    includeGithubPagesConfig: true,
    includeSitemap: true,
    includeCyberShield: true,
  }
): Promise<Blob> {
  const zip = new JSZip();
  const brand = portalConfig.siteName || ampConfig.brandName || 'OFFICIAL VIP';

  // 1. Generate Individual HTML Strings
  const ampHtml = generateAmpHtml({ ...ampConfig, cyberShield: cyberShieldConfig });
  const portalHtml = generatePortalHtml(
    { ...portalConfig, cyberShield: cyberShieldConfig },
    cdnScripts.scripts
  );
  const registerHtml = generateVipRegisterHtml(
    { ...registerConfig, cyberShield: cyberShieldConfig },
    cdnScripts.scripts
  );
  const safelinkHtml = generateSafeLinkHtml(
    { ...safelinkConfig, cyberShield: cyberShieldConfig },
    cdnScripts.scripts
  );
  const cyberShieldJs = generateCyberShieldScript(cyberShieldConfig, brand);

  // 2. Primary index.html
  const primaryHtml = options.primaryLanding === 'amp' ? ampHtml : portalHtml;
  zip.file('index.html', primaryHtml);

  // 3. Named page files
  zip.file('amp.html', ampHtml);
  zip.file('portal.html', portalHtml);
  zip.file('register.html', registerHtml);
  zip.file('safelink.html', safelinkHtml);

  // 4. Standalone CyberShield module
  if (options.includeCyberShield) {
    zip.file('cyber-shield.js', cyberShieldJs);
  }

  // 5. SEO & Crawlers
  const robotsTxt = generateRobotsTxt(ampConfig.canonicalUrl || 'https://vip-official.pages.dev/');
  zip.file('robots.txt', robotsTxt);

  if (options.includeSitemap) {
    const sitemapXml = generateSitemapXml(
      ampConfig.canonicalUrl || 'https://vip-official.pages.dev/',
      portalConfig.primaryCtaUrl || ''
    );
    zip.file('sitemap.xml', sitemapXml);
  }

  // 6. Cloudflare Pages configs
  if (options.includeCloudflareConfig) {
    zip.file('_redirects', generateCloudflareRedirects());
    zip.file('_headers', generateCloudflareHeaders());
  }

  // 7. Apache / cPanel .htaccess
  if (options.includeHtaccess) {
    zip.file('.htaccess', generateHtaccess(brand));
  }

  // 8. GitHub Pages
  if (options.includeGithubPagesConfig) {
    zip.file('.nojekyll', '');
  }

  // 9. Documentation
  zip.file('README.md', generateReadmeDeployment(brand));

  return await zip.generateAsync({ type: 'blob' });
}
